server:
    port: 8080

eureka:
    instance:
        prefer-ip-address: true

spring:
    application:
        name: gateway-service
    cloud:
        gateway:
            routes:
                -   id: userServiceRoute
                    uri: lb://user-service
                    predicates:
                        - Path=/user-service/**
                    filters:
                        - StripPrefix=1

                -   id: gamblingServiceRoute
                    uri: lb://gambling-service
                    predicates:
                        - Path=/gambling-service/**
                    filters:
                        - StripPrefix=1

                -   id: invoiceServiceRoute
                    uri: lb://invoice-service
                    predicates:
                        - Path=/invoice-service/**
                    filters:
                        - StripPrefix=1

                -   id: documentServiceRoute
                    uri: lb://document-service
                    predicates:
                        - Path=/document-service/**
                    filters:
                        - StripPrefix=1