server:
    port: 9000
eureka:
    instance:
        prefer-ip-address: true
spring:
    application:
        name: user-service

    r2dbc:
        url: r2dbc:mariadb://localhost:3306/user-service
        username: root
        password: root

    flyway:
        encoding: UTF-8
        out-of-order: true
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0
