server:
    port: 0
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${random.value}
spring:
    application:
        name: user-service

    r2dbc:
        url: r2dbc:mariadb://localhost:3306/user-service
        username: root
        password: root

    flyway:
        encoding: UTF-8
        out-of-order: true
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0
        url: jdbc:mariadb://localhost:3306/user-service
        password: root
        user: root
