version: '3.7'
services:
    mongo:
        image: mongo:4.2
        networks:
            - casino-network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
        ulimits:
            memlock:
                soft: -1
                hard: -1
        deploy:
            resources:
                limits:
                    memory: 1g
        networks:
            - casino-network


    graylog:
        image: graylog/graylog:4.2
        environment:
            - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
            - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
        entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
        networks:
            - casino-network
        restart: always
        depends_on:
            - mongo
            - elasticsearch
        ports:
            - "9000:9000"
            - "1514:1514"
            - "1514:1514/udp"
            - "12201:12201"
            - "12201:12201/udp"

networks:
    casino-network:
        driver: bridge
        name: casino-network