server:
    port: 0
eureka:
    instance:
        prefer-ip-address: true
spring:

    rabbitmq:
        username: guest
        password: guest

    cloud:
        function:
            definition: gamblingServiceMessage
        stream:
            bindings:
                gamblingServiceMessage-in-0:
                    group: in
                    destination: invoice-service

    application:
        name: invoice-service

    r2dbc:
        url: r2dbc:mariadb://localhost:3306/invoice-service
        username: root
        password: root

    flyway:
        encoding: UTF-8
        out-of-order: true
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0
        url: jdbc:mariadb://localhost:3306/invoice-service
        password: root
        user: root