server:
    port: 8000

spring:
    application:
        name: invoice-server
    r2dbc:
        url: r2dbc:mariadb://localhost:3306/invoice-service
        username: root
        password: root

    flyway:
        encoding: UTF-8
        out-of-order: true
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0

