server:
    port: 8000

spring:
    datasource:
        url: jdbc:mariadb://localhost:3306/invoice-service
        username: root
        password: root
        driver-class-name: org.mariadb.jdbc.Driver

    flyway:
        encoding: UTF-8
        out-of-order: true
        enabled: true
        baseline-on-migrate: true
        baseline-version: 0

