server:
    port: 0

eureka:
    instance:
        prefer-ip-address: true

spring:
    application:
        name: gambling-service

    rabbitmq:
        username: guest
        password: guest

app:
    loss_probability: 0.51